"""Publishing and safety validation for the agent runner."""

from __future__ import annotations

from fnmatch import fnmatch
from pathlib import Path

from backend.core.shared.interfaces.agent_runner import (
    IContentGenerator,
    IGitHubClient,
    IProcessRunner,
)
from backend.core.shared.models.agent_runner import AppConfig, IssueSummary
from backend.core.use_cases.agent_runner_git import (
    get_current_branch,
    list_changed_paths,
    list_git_remotes,
)
from backend.core.use_cases.generated_content import (
    build_pr_context,
    generate_pr_content,
)

__all__ = [
    "publish_changes",
    "run_preflight_checks",
    "validate_publish_remote",
    "validate_safe_changes",
]


def validate_safe_changes(
    worktree_path: Path,
    config: AppConfig,
    process_runner: IProcessRunner,
) -> None:
    """Refuse to publish changes to configured forbidden paths."""
    blocked_paths: list[str] = []
    for changed_path_text in list_changed_paths(worktree_path, process_runner):
        changed_path_name = Path(changed_path_text).name
        for forbidden_pattern in config.safety.forbidden_path_patterns:
            if fnmatch(changed_path_text, forbidden_pattern) or fnmatch(
                changed_path_name,
                forbidden_pattern,
            ):
                blocked_paths.append(changed_path_text)
                break
    if blocked_paths:
        blocked_paths_text = ", ".join(sorted(set(blocked_paths)))
        raise RuntimeError(f"Refusing to publish forbidden paths: {blocked_paths_text}")


def validate_publish_remote(
    worktree_path: Path,
    config: AppConfig,
    process_runner: IProcessRunner,
) -> str:
    """Return the configured publish remote after confirming it exists."""
    remote_names = list_git_remotes(worktree_path, process_runner)
    configured_remote_name = config.git.remote
    if configured_remote_name in remote_names:
        return configured_remote_name

    available_remotes_text = ", ".join(remote_names) if remote_names else "(none)"
    raise RuntimeError(
        "Configured git remote "
        f"'{configured_remote_name}' does not exist. "
        f"Available remotes: {available_remotes_text}. "
        "Update [agent_runner.git].remote in .iar.toml or config.toml before publishing."
    )


def run_preflight_checks(
    repo_path: Path,
    config: AppConfig,
    process_runner: IProcessRunner,
) -> None:
    """Validate runner configuration before claiming any Issue."""
    validate_publish_remote(repo_path, config, process_runner)


def publish_changes(
    issue: IssueSummary,
    worktree_path: Path,
    config: AppConfig,
    github_client: IGitHubClient,
    process_runner: IProcessRunner,
    *,
    expected_branch: str | None = None,
    content_generator: IContentGenerator | None = None,
) -> tuple[str, str]:
    """Push and create a draft PR. Assumes the agent has already committed.

    在 push 前再次执行安全检查（validate_safe_changes），
    防止 agent 在 commit 后、push 前的间隙修改了 forbidden paths。

    Args:
        issue: 当前处理的 Issue。
        worktree_path: agent 工作的 git worktree 路径。
        config: Agent Runner 配置。
        github_client: GitHub 客户端。
        process_runner: 命令执行器。
        expected_branch: 期望的分支名，用于防止分支漂移。
        content_generator: 可选的 AI 内容生成器，用于生成 PR 标题和描述。

    Returns:
        (分支名, PR URL) 元组。

    Raises:
        RuntimeError: 分支不匹配或远程不存在。
    """
    branch = get_current_branch(worktree_path, process_runner)
    if expected_branch is not None and branch != expected_branch:
        raise RuntimeError(
            f"Refusing to publish from unexpected branch: {branch} "
            f"(expected {expected_branch})"
        )
    # push 前再次检查 forbidden paths，防止 commit 后又被修改
    validate_safe_changes(worktree_path, config, process_runner)
    publish_remote_name = validate_publish_remote(worktree_path, config, process_runner)
    process_runner.run(
        ["git", "push", "-u", publish_remote_name, branch], cwd=worktree_path
    )

    fallback_title = f"[Agent] {issue.title}"
    fallback_body = f"Closes #{issue.number}\n\nGenerated by issue-agent-runner.\n"

    gc_config = config.generated_content
    pr_title = fallback_title
    pr_body = fallback_body
    if gc_config.enabled:
        gc_context = build_pr_context(
            issue=issue,
            branch=branch,
            base_branch=config.git.base_branch,
            worktree_path=worktree_path,
            process_runner=process_runner,
            target_config=gc_config.draft_pr,
        )
        generated = generate_pr_content(
            config=gc_config,
            context=gc_context,
            fallback_title=fallback_title,
            fallback_body=fallback_body,
            generator=content_generator,
            cwd=worktree_path,
        )
        pr_title = generated.title
        pr_body = generated.body

    pr_url = github_client.create_draft_pr(
        title=pr_title,
        body=pr_body,
        base_branch=config.git.base_branch,
        cwd=worktree_path,
    )
    return branch, pr_url
